### ISSUE TITLE
[FR] Ability to customize code snippets and responses.

### ISSUE THREAD

**Issue by sradu** [PaloAltoNetworks/docusaurus-openapi-docs#169]
### Is your feature request related to a problem?

Would be great to have the code snippets similar to stoplight. I'm also not seeing the 'Response' but perhaps that's a separate bug.

### Describe the solution you'd like

I've attached some images. 

<img width="490" alt="Screen Shot 2022-07-21 at 10 05 44 PM" src="https://user-images.githubusercontent.com/82214/180296099-b6fb7886-8f6b-4d71-a115-5a333fe7c3ae.png">

<img width="491" alt="Screen Shot 2022-07-21 at 10 05 49 PM" src="https://user-images.githubusercontent.com/82214/180296125-f338cca8-3ded-45fa-88de-255d5d9a6c40.png">

### Describe alternatives you've considered

I'm trying to figure out how to theme it so it looks more similar to the screenshots. Haven't found a library that generates the client code yet.

**Comment by sserrata** [comment]
Hi @sradu, thanks for the FR! We use a forked [postman-code-generators](https://github.com/PaloAltoNetworks/postman-code-generators) under the hood and do have the ability to support other languages. That said, we're being careful about how we introduce language support in order to control the overall webpack bundle size, i.e. keep it from inflating so much it impacts performance. Unfortunately, `postman-code-generators` doesn't really lend itself to tree shaking or optimization in this way - it's kind of "all or nothing" in that regard.

It's on our roadmap to look deeper into how to support other languages but, from experience, we also believe it's more important to provide coverage for the languages actually in use by the developer audience you're looking to reach/support. That said, our next move might be to allow users to define which languages they want to support in the plugin config.

As for response examples, we have an issue opened for that: #119

**Comment by sradu** [comment]
Thanks Steven! I fully agree that having 4-5 snippets would be OK. For instance Curl, Ruby, Python, PHP, Javascript, Node, Go, .NET. Stripe has a similar way of doing it, a dropdown with a cookie to remember the choice.

<img width="668" alt="Screen Shot 2022-07-22 at 1 56 40 PM" src="https://user-images.githubusercontent.com/82214/180425315-23242925-3cf6-453f-9229-55d499e32fff.png">

Perhaps instead of tabs + logos this seems like a more common approach. Not having those logos would also decrease the bundle size.

**Comment by sserrata** [comment]
I agree that, it we're to support >4 languages, a dropdown seems like a better UI/UX choice. I should mention that we are trying, whenever possible, to stick to the Infima CSS framework that Docusaurus is based on, in order to maintain UI/UX consistency while allowing the user to customize the styles in a consistent way with the rest of the Docusaurus site. That said, we may also introduce new, custom components not already included in Infima.

**Comment by sserrata** [comment]
Found an interesting project that could be a better/lighter-weight alternative: https://github.com/Kong/httpsnippet

It is based on the HAR format but it should be fairly easy to integrate with.
