### ISSUE TITLE
How do I display request types and show description instead of operationId in my sidebar?

### ISSUE THREAD

**Issue by Jaxkr** [PaloAltoNetworks/docusaurus-openapi-docs#177]
## Documentation link

On the example (https://docusaurus-openapi.tryingpan.dev/petstore/update-pet-with-form) the sidebar items display the request type (POST, GET, etc.).

## Describe the problem

The docs at https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/README.md nor the example configuration at https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/demo/docusaurus.config.js show how this sidebar configuration was achieved.

## Suggested fix

Document the configuration options for:
1. Determining page display title
2. Showing request types in the sidebar.

**Comment by sserrata** [comment]
Hi @Jaxkr, the method badges are the result of some custom CSS. Feel free to copy ours or customize it to your liking:

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/demo/src/css/custom.css#L45

As for "displaying descriptions instead of operationId," I think you're referring to these:

<img width="298" alt="Screen Shot 2022-07-29 at 9 09 27 AM" src="https://user-images.githubusercontent.com/9343811/181767238-c5a7099f-3e6e-4ca8-ad52-7d7f112e8bee.png">

The sidebar item labels are based on the path/operation `summary` value and default to the `operationId` if the `summary` does not exist. Is it possible your OpenAPI specification may be missing the `summary` for each path?

**Comment by sserrata** [comment]
Also, thanks for pointing this out. We'll be sure to add this to the documentation.

**Comment by sserrata** [comment]
Will use #182 to track documentation effort.
