### ISSUE TITLE
Not all tags are extracted from the OpenAPI document

### ISSUE THREAD

**Issue by skyfrk** [PaloAltoNetworks/docusaurus-openapi-docs#257]
## Describe the bug

I am using [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) to generate an OpenAPI document for my API. If I use the generated spec with this plugin the `sidebar.js` contains only one entry, because the `tags` property is not defined in my document.

According to the v3.0.3 OpenAPI spec not all tags must be defined in the `tags` property:

> A list of tags used by the specification with additional metadata. The order of the tags can be used to reflect on their order by the parsing tools. **Not all tags that are used by the [Operation Object](https://swagger.io/specification/#operation-object) must be declared.** The tags that are not declared MAY be organized randomly or based on the tools' logic. Each tag name in the list MUST be unique.

## Expected behavior

[processOpenapiFile](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/02922a6ad6d635373e01409dac8c17a88da2b72e/packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts#L351) should iterate all `paths` and `operations` and collect tags and merge them with the tags defined in the `tags` property.

## Current behavior

[processOpenapiFile](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/02922a6ad6d635373e01409dac8c17a88da2b72e/packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts#L351) just checks the `tags` property

## Your Environment

- Version used: `v1.1.11`
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): nodejs `v16.15.1`

**Comment by sserrata** [comment]
Hi @skyfrk, thanks for reporting this issue. Currently, the plugin requires tags to be defined under the root `tags` object. It does this for two reasons:

* To allow for using the root tag description as the `categoryLinkSource` (which is optional).
* To reconcile and ensure consistency between the operation tag(s) and the tags defined under `tags` (kind of a weak use case since if an operations tag doesn't match that path could be ignored). 

Since we are already generating a unique array of operations tags, it should be relatively easy to eliminate the requirement to also define them under the root `tags`. We'll look into this and keep you posted. Thanks!

**Comment by skyfrk** [comment]
I agree that there is no strong use case. For my personal use I just derived the list of tags from all operations as a workaround.
