### ISSUE TITLE
Cannot render <br> to create new lines in openapi path description

### ISSUE THREAD

**Issue by AviandraPutri-Jubelio** [PaloAltoNetworks/docusaurus-openapi-docs#299]
Hi, just want to tell you that when I use **<.br.>** (sorry if I use a dot, but the actual is without a dot) or **<br  />** in my OpenAPI path description, it seems that it cannot be rendered as a new line. 

![image](https://user-images.githubusercontent.com/111033787/196143949-598ec3b6-6b1b-4f5e-bcc2-638b3d4d1cfd.png)

Do you have any ideas about what is wrong and what I should do to create new line?

**Comment by sserrata** [comment]
Hi @AviandraPutri-Jubelio, can you share a snippet or link to your OpenAPI spec? Generally speaking, Docusaurus-style inline HTML-in-markdown/MDX should be supported but there are cases where it won't be fully supported.

**Comment by sserrata** [comment]
Actually, I think I isolated the root case. We are intentionally escaping special characters by HTML-encoding them, such that their literal string representation can be displayed. This decision was made in order to avoid build issues when descriptions contained HTML-like characters, like when using `<` and `>` to denote variables or placeholders. 

Examples:
* Denoting variables like this: This is a \<variable\>
* Using symbols in a path to denote path variables like this: /api/pet?type=\<type\>&breed=\<breed\>

The build errors occur because Docusaurus interprets them as HTML/JSX tags.

The short term solution would be to avoid inline HTML/JSX but I can see how this can be limiting.

I'm going to run a few tests to see if we can safely remove the `escape()` dependency without any breaking side effects.

**Comment by sserrata** [comment]
v1.3.1 now includes the fix

**Comment by AviandraPutri-Jubelio** [comment]
Yes, it is now successfully rendered <.br /> into a new line! Yuhuu, thank you so much!
