### ISSUE TITLE
OpenAPI pages are crashed with Docusaurus v2.2.0

### ISSUE THREAD

**Issue by hdkshingala** [PaloAltoNetworks/docusaurus-openapi-docs#323]
## Describe the bug

The OpenAPI pages are crashing when we upgraded the Docusaurus from v2.1.0 to v2.2.0.

## Expected behavior

The plugin should work fine and should show the pages correctly.

## Current behavior

The OpenAPI related pages get crashed with below error:

![image](https://user-images.githubusercontent.com/34568645/199954028-a2f963fe-d8e7-4b11-a2f5-15af8633a2f7.png)

## Steps to reproduce

1. Run plugin v1.2.2 with Docusaurus v2.2.0.

## Your Environment

- Version used: v1.2.2.
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): nodejs 18.11, Ubuntu 22.04
- Operating System and version (desktop or mobile): Desktop
- Link to your project: https://github.com/fluxninja/aperture

We have tried using the latest v1.4.1 but faced https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/315 so couldn't check with the latest version.

**Comment by calthejuggler** [comment]
I'm having the same issue, and I also can't run the `docusaurus build` command. I'm getting the following error:
`[ERROR] Docusaurus server-side rendering could not render static page with path /docs/SDK API/collector-health-check.`

I'm thinking it's something to do with the `.api` suffix on the openapi filenames?

**Comment by sserrata** [comment]
@hdkshingala thanks for reporting the issue. Although Docusaurus is supposed to respect semantic versioning now, they apparently still introduce breaking changes, at least for plugin maintainers. The fix for supporting v2.2.0 should be straightforward but I am not sure how we can make it backwards compatible with v2.1.0 and v2.0.1.

@calthejuggler, v2.2.0 is currently not supported due to a breaking change introduced by Docusaurus. That is why the build fails.

**Comment by sserrata** [comment]
Hi all, just merged support for v2.2.0 into main. Would appreciate if anyone could test using canary release `0.0.0-505`. Thanks!

**Comment by thomasheartman** [comment]
@sserrata This _may_ be unrelated, but I think it's a continuation of the same issue. I've been having some issues today (as mentioned in #337), but I've found a potential workaround and have made some progress. As far as I've gotten now, I've tried out both `1.4.3` and canary `0.0.0-506` with docusaurus 2.2.0. 
- With 1.4.3, I'd get the same error as listed above (except it would happen in the build chain (`docusaurus build`))
- With 0.0.0-506, I'm getting a different error: `Hook useDoc is called outside the <DocProvider>. `

From what I can tell, your first fix was successful, but there's more hooks that have been moved around. I've been trying to connect the threads, and it seems somewhat related to what's mentioned in [this issue about a similar breakage](https://github.com/facebook/docusaurus/issues/7686#issuecomment-1169917361).

**Comment by sserrata** [comment]
Hi @thomasheartman, can you share your upgrade path or process? I noticed that if you run the suggested upgrade commands (pictured below) that not all dependencies are upgraded to 2.2.0. I'm still experimenting but I found that simply running `yarn upgrade` clears it up.

Upgrading this way seems to not update all Docusaurus dependencies to 2.2.0:

<img width="1119" alt="Screen Shot 2022-11-10 at 8 43 05 AM" src="https://user-images.githubusercontent.com/9343811/201107364-0ed35c61-718d-4162-90b7-d6a5b6a40a3d.png">

**Comment by thomasheartman** [comment]
@sserrata So I've tried again and also made sure that all the deps are on the same version. it runs fine in development mode, but when running docusaurus build, it fails. Does that sound familiar?

**Comment by sserrata** [comment]
What version of `docusaurus-openapi-docs` were you on before? Depending on upgrade path you might need to re-gen the API docs.

**Comment by thomasheartman** [comment]
I've tried 1.4.3 and 1.4.1. I think I've regenerated the API docs every time, but I'll give it another go just to make sure 🙋🏼

**Comment by thomasheartman** [comment]
Update: regenerating the docs doesn't seem to have any effect.

**Comment by sserrata** [comment]
Is it still working in dev? What's the build error you're seeing?

**Comment by sserrata** [comment]
If you haven't already, you might want to try some variation of:

```
rm -rf node_modules
rm -rf .docusaurus
rm yarn.lock
yarn
yarn upgrade
```

**Comment by thomasheartman** [comment]
Yeah, it builds fine in dev and visiting the generated pages doesn't cause any issues either.

The error I'm seeing is:

```
$ docusaurus build
[INFO] [en] Creating an optimized production build...

✔ Client


✖ Server
  Compiled with some errors in 40.85s



TypeError: source_default(...).bold is not a function
TypeError: source_default(...).bold is not a function
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Users/thomas/projects/work/unleash/website/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Users/thomas/projects/work/unleash/website/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/thomas/projects/work/unleash/website/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[INFO] Docusaurus version: 2.2.0
Node version: v16.14.0
error Command failed with exit code 1.
```

Which isn't very helpful at all. if I go into `/node_modules/@docusaurus/core/lib/client/serverEntry.js` and modify the compile function to log the actual error and remove anything chalk-related, I get this instead:

```
$ docusaurus build
[INFO] [en] Creating an optimized production build...

✔ Client


✖ Server
  Compiled with some errors in 44.62s

Actual error: Error: Unexpected: cant find current sidebar in context
    at useCurrentSidebarCategory (main:11618:247)
    at MDXContent (main:38139:1593)
    at Fb (main:149154:44)
    at Ib (main:149156:254)
    at W (main:149162:89)
    at Jb (main:149165:98)
    at Ib (main:149157:145)
    at W (main:149162:89)
    at Jb (main:149165:98)
    at Ib (main:149157:145)
Actual error: Error: Unexpected: cant find current sidebar in context
    at useCurrentSidebarCategory (main:11618:247)
    at MDXContent (main:38513:1469)
    at Fb (main:149154:44)
    at Ib (main:149156:254)
    at W (main:149162:89)
    at Jb (main:149165:98)
    at Ib (main:149157:145)
    at W (main:149162:89)
    at Jb (main:149165:98)
    at Ib (main:149157:145)


Error: Unexpected: cant find current sidebar in context
Error: Unexpected: cant find current sidebar in context
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Users/thomas/projects/work/unleash/website/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Users/thomas/projects/work/unleash/website/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/thomas/projects/work/unleash/website/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[INFO] Docusaurus version: 2.2.0
Node version: v16.14.0
error Command failed with exit code 1.
```

After clearing `node_modules`, `.docusarus`, and `yarn.lock`, reinstalling and upgrading, and _then_ regenerating the files, I'm still getting the error when running `docusaurus build` and still not when running `docusaurus start`.

**Comment by sserrata** [comment]
The plot thickens...now I am seeing the same error but only when attempting to build the demo locally:

```
Error: Unexpected: cant find current sidebar in context
```

The weird thing is that it build in prod and in deploy previews.

**Comment by sserrata** [comment]
Update: ended up being caused by some old generated files I forgot to cleanup in between tests. Worked after I deleted them.

**Comment by thomasheartman** [comment]
Thanks, @sserrata! Unfortunately, we're seeing the issue both locally and when building docs in CI. I've also completely removed the generated directories a few times to avoid having outdated files lying around. We **did** have a similar issue once before, where it was caused by an empty file, but `find -type f -empty` doesn't yield any results in this case, so I **don't** think that's the issue in this case.

**Comment by thomasheartman** [comment]
So I'm making some progress, and it looks like the error _is_ indeed related to this package: I found that 

1. If I remove all generated files and remove the sidebar reference from my sidebars.js file, then it compiles without issue.
2. If I add the generated files, but not the sidebar reference, I get the same error as reported previously (can't find current sidebar), but I get **23** instances of the error.
3. If I add the sidebar reference, I only get **2** instances of the error.

So I'm thinking that it may be related to the configuration somehow. For reference, here's what I'm using:

## Configuration

In **`docusaurus.config.js`**:
```js
    plugins: [
        // elided: redirect plugin configuration
        [
            'docusaurus-plugin-openapi-docs',
            {
                id: 'api-operations',
                docsPluginId: 'classic',
                config: {
                    server: {
                        specPath: 'https://us.app.unleash-hosted.com/ushosted/docs/openapi.json',
                        outputDir: 'docs/reference/api/unleash',
                        sidebarOptions: {
                            groupPathsBy: 'tag',
                            categoryLinkSource: 'tag',
                        },
                    },
                },
            },
        ],
    ],
    themes: ['docusaurus-theme-openapi-docs']
```

In **`sidebars.js`**:
```js
                        {
                            label: 'OpenAPI docs',
                            collapsed: true,
                            type: 'category',
                            link: {
                                title: 'Unleash Server APIs',
                                type: 'generated-index',
                                description:
                                    'Generated API docs based on the Unleash OpenAPI schema.',
                                slug: '/reference/api/unleash',
                            },
                            items: require('./docs/reference/api/unleash/sidebar.js'),
                        }
```

As mentioned in the file, the source spec we use for generation is `https://us.app.unleash-hosted.com/ushosted/docs/openapi.json`.

Does that look right? Is there something that stands out to you as potentially causing these issues?

----

@sserrata I also realize that this is probably not the same issue as the one the OP reported anymore: should I open another one? Sorry for overtaking this thread 🙇🏼

**Comment by thomasheartman** [comment]
@sserrata I think I found the issue 🙋🏼 I'll try and explain it here, but in short: the plugin generated two tag files it didn't reference. That would also explain why sidebar reference couldn't be found.

## The root cause

The OpenAPI spec we use to generate the docs has a number of tags listed at the root level. This is necessary for this plugin to pick up tag categories and is, as far as I can tell, also how it _should_ be done.

However, not all of those tags are in use. Specifically, there's 2 tags that are not.

When the plugin generates docs from the spec, it generates pages for all endpoints and all tags and groups them by tag. However, it seems likely that if a tag doesn't have any associated endpoints, then it won't get added to the sidebar because there's no endpoint that references it.

But the doc files for these tags do end up lying around in the directory regardless, and when docusaurus tries to pick up the files in the generated directory, it also tries to pick up the unused tag files. But because they're not part of a sidebar, they end up throwing errors because they can't find the sidebar context.

## How I found it

The fact that I got more instances of the error message without the sidebar ref than with it made me pay more attention to the number of errors. I decided to check how many files were in the generated directory and how many files were referenced from the generated sidebar. Turns out the difference there was **2**: there were two generated files in the directory that the sidebar didn't reference. 

At this point, it was easy enough to try and delete those files before rebuilding, and wouldn't you know: it worked!

## Our use case

Now, why do we have tags that are unused in the root spec? Can't we just remove them?

That's a good question with a bit of a complicated answer. Unleash uses an open core model and the OpenAPI integration is part of that open core. The closed-source parts of Unleash are located in another repo and extend the open-source distribution. 

Because the OpenAPI spec is configured in the open-source part, enterprise-only tags etc also need to be configured there. Then, when the changes are absorbed into enterprise, we can use the tags there.

It gets more complicated because we use an enterprise instance to generate the docs (because we want enterprise-endpoints to be listed too). The instance uses the latest released instance of Unleash to have the docs most accurately reflect the current state of things.

So, in this case, the tags have been added, but not yet used by any endpoints, which suddenly causes this build failure. We can add the tags to the enterprise-version, but the spec wouldn't be updated before the next release regardless, which will probably be in a week or so. 

This isn't an ideal setup, but .. it is what it is.

I'll make some changes now to try and remove any tags we don't actually use, but it'll take some time for the changes to propagate.

## Expectations for this plugin

I would not expect the plugin to cause compilation issues when this happens. It could certainly log some warnings if it wanted (during doc generation process), but it shouldn't stop the build from working.

I think I would expect one of these two outcomes:
1. Files that aren't referenced by the sidebar are removed at the end of the generation process
2. Tags without any files are created as empty category placeholders

----

What do you think? I'd consider this a bug with the plugin, but I'm happy for you to have a different take on it. Feel free to spin this out into a separate issue if you want to 😄

**Comment by sserrata** [comment]
Hi @thomasheartman, thanks for the detailed write up - you helped me understand that this is a regression bug introduced in #276. I think it can be refactored to exclude any global tags that are _not_ referenced by an operation.

**Comment by thomasheartman** [comment]
> Hi @thomasheartman, thanks for the detailed write up - you helped me understand that this is a regression bug introduced in #276. I think it can be refactored to exclude any global tags that are _not_ referenced by an operation.

Yes, that should cover it 😁 🙌

**Comment by sserrata** [comment]
@thomasheartman fix is included in `0.0.0-513` is you want to test before next release.

**Comment by thomasheartman** [comment]
Wow, amazing! I'll give it a spin on Monday and look forward to the next release, then 😄  Is there a scheduled date for it (or a rough estimation)?

**Comment by sserrata** [comment]
> Is there a scheduled date for it (or a rough estimation)?

It's available now: v1.4.4

**Comment by thomasheartman** [comment]
Legend 🔥

**Comment by hdkshingala** [comment]
Upgraded out setup to Docusaurus 2.2.0 and Plugin v1.4.4 and it is working as expected now.

Thanks a lot @sserrata for providing a real quick.

**Comment by sserrata** [comment]
@aj-hops You'll need to upgrade to the `2.0.0-beta` for `2.3.1` support. The latest release is `2.0.0-beta.1`.
