### ISSUE TITLE
getting a type error when trying to generate docs 

### ISSUE THREAD

**Issue by kasserXX99** [PaloAltoNetworks/docusaurus-openapi-docs#378]
## Describe the bug
when I'm trying my own swagger or yaml file to generates docs I'm always getting a type error , however when I use the the petstore yaml it's working fine , is there any format  that I should follow ? 

this is the error from the terminal 
`[ERROR] TypeError: Cannot read properties of undefined (reading 'replace')
    at /Users/amer/paymentGateWayTest/docsPage/dineropay-staging/node_modules/docusaurus-plugin-openapi-docs/lib/index.js:206:29
    at Array.map (<anonymous>)
    at generateApiDocs (/Users/amer/paymentGateWayTest/docsPage/dineropay-staging/node_modules/docusaurus-plugin-openapi-docs/lib/index.js:188:23)
    at async /Users/amer/paymentGateWayTest/docsPage/dineropay-staging/node_modules/docusaurus-plugin-openapi-docs/lib/index.js:362:29`

## Expected behavior
docs to be generated

## Current behavior
A type error cause the plugin to be crashed

## Steps to reproduce

1. npm run  docusaurus clean-api-docs all
2.
3.
4.

## Screenshots
<img width="856" alt="Screen Shot 2023-01-06 at 7 37 32 PM" src="https://user-images.githubusercontent.com/69112877/211056438-9d6ce44a-5301-4a79-a9da-faa2600a8dc6.png">

**Comment by deyanp** [comment]
@kasserXX99 what was the fix for this? I am getting the same error, but also for petstore from the demo project ...

**Comment by wojski** [comment]
If anyone has a similar issue in the future.
It's happening because in the default configuration has defined: `docsPluginId: "classic"`.
In that case, code will try to resolve the path with `docs/petstore` but the doccumentation suggests that it will be `api/petstore`.

To fix that just change to `docsPluginId: "api"`

It's also related in doc:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/15378309/215908882-3fd36b11-f447-4b62-af8b-d28b47185a1c.png">

**Comment by kasserXX99** [comment]
thanks for sharing that I think that was the issue I'll give it a try and update here .

**Comment by rojakcoder** [comment]
I had this error as well. Can confirm that changing to `docsPluginId: "api"`solved the problem.
