### ISSUE TITLE
[FR] Add class to response tabs to differentiate success/error

### ISSUE THREAD

**Issue by IanVS** [PaloAltoNetworks/docusaurus-openapi-docs#460]
### Is your feature request related to a problem?

I want to have a design like this:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/4616705/221627858-1d72df72-9df8-4a29-a53d-7ec7ef55d715.png">

Where the color and background of the `<li>` is determined by the success/danger class.  Currently, those are set on a dot, which is a child of the list item.  In modern browsers except Firefox, I can use the `:has()` selector to target the parent, but that does not work in Firefox or older browsers.

### Describe the solution you'd like

I'd like if a class was set on the `li` itself, and then the dot can use that class to know what color it should be.  This would allow styling the li as well as the dot.

### Describe alternatives you've considered

The class of the dots don't need to change either, in case others are relying on them already.  Adding an additional class to the `li` should be enough for me.

**Comment by blindaa121** [comment]
Hi @IanVS, thank you for the suggestion! This is actually a part of the long-standing PR for our upcoming `2.0.0` release which also includes adding BEM classes throughout the project. Since this should be a quick fix, we can patch this into an earlier release for `1.6.1`. I'll keep you updated with the status 👍
