### ISSUE TITLE
Add `--config` and `[siteDir]` option

### ISSUE THREAD

**Issue by Dr-Electron** [PaloAltoNetworks/docusaurus-openapi-docs#490]
### Is your feature request related to a problem?

Currently, we can't run the gen-api command in the same folder as we have the config, and our config has a different name.
For the built-in start/build command in Docusaurus we therefore use the above-mentioned arguments.

### Describe the solution you'd like

Would be nice to pass the `siteDir` and `config` option to the gen-api command as well

**Comment by sserrata** [comment]
Hi @Dr-Electron, so if I am understanding correctly, when you pass these options to `docusaurus` they are not propagating to `docusaurus-plugin-openapi-docs`?

For example: `yarn docusaurus --config path/to/docusaurus.config.js --siteDir /my/siteDir gen-api-docs all`

**Comment by sserrata** [comment]
Hi @Dr-Electron, was really just wanting to confirm the issue/behavior you are observing. I am not too familiar with the `--config` and `--siteDir` options. Can you share the command(s) you are attempting to run or more context? Thanks!

**Comment by Dr-Electron** [comment]
Yeah. So as I said the `docusaurus start` command for example has the `--config` and `[siteDir]` option.
So now let's imagine for whatever reason the docusaurus.config.js is in a subfolder or has a different name.
To `start` the deployment I would run for example: `yarn docusaurus start --config some-other-name.js`.
But now how would I use `gen-api-docs` in this setup? I can't pass a different config name or directory to it

**Comment by sserrata** [comment]
Thanks for the clarification. Not exactly sure how to support this since the Docusaurus config is read in before the OpenAPI plugin. I suspect this is more of a limitation in the Docusaurus CLI than it is a feature gap in our plugin. Perhaps the best step forward would be to open a feature request to request moving/supporting the `--config` option at the `docusaurus` level. 

Today, it only appears to be supported at the command level, i.e. `build`, `start`, `swizzle`, etc. I suspect this could be the result of there not being many community plugins that extend the CLI, hence why they may have overlooked this use case. Interested to hear your thoughts on the matter.

**Comment by Dr-Electron** [comment]
I never really used the docusaurus cli or looked at its code. So to me it seemed this would be a plugin issue. So thanks for clarifying this.
I will check the source code of the cli and talk with the docusaurus team. Is it fine if I keep this issue open in the meantime as a reference and we can hopefully close everything together later on?

**Comment by SirPhemmiey** [comment]
Hello, does anyone have an update on this?

**Comment by slorber** [comment]
In https://github.com/facebook/docusaurus/pull/10685 I'm adding escape hatch env variables that could help you execute plugin code in other (non-cwd) siteDir and using custom config file names:

- `DOCUSAURUS_CLI_SITE_DIR`
- `DOCUSAURUS_CLI_CONFIG`

This is likely not the final implementation but the only idea I have without a breaking change. Should be in the upcoming v3.6.2
