### ISSUE TITLE
Schemas sections like in the default swagger UI

### ISSUE THREAD

**Issue by etiennea** [PaloAltoNetworks/docusaurus-openapi-docs#593]
### Is your feature request related to a problem?

This is really missing, Schemas reference. 
Ideally with the ability to filter. We use nestjs and so we have both Entities and DTO schemas. 
Would be a great addition. 

### Describe the solution you'd like

A new sidebar menu with the list of Schemas so one can jump in them directly. 
An option to enable/disable this. 
An option to filter these for example only those containing "Entity"
The rendering of the Schemas is already supported in the endpoints so this should not be too complex to do. 

### Describe alternatives you've considered

No good alternatives

### Additional context

Requested by my product team for our docs, to better keep track of our domain.

**Comment by sserrata** [comment]
Hi @etiennea, this is one of the more requested features we've seen so far. That said, since our plugin already attempts to fully resolve operation request/response schemas, I wonder how valuable this feature could actually be? Are there schemas not referenced by endpoints that you would also want to document?

**Comment by sserrata** [comment]
already addressed
