### ISSUE TITLE
No serializer registered for ProvidedDependency

### ISSUE THREAD

**Issue by tiero** [PaloAltoNetworks/docusaurus-openapi-docs#598]
##  No serializer registered for ProvidedDependency

I am getting warnings when running `yarn dev` with this plugin enabled

```sh
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/Users/tiero/projects/prem/dev-portal/node_modules/webpack/hot/log.js': No serializer registered for ProvidedDependency
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 12 items } -> ProvidedDependency
```

## Your Environment

- docusaurus
```
"@docusaurus/core": "2.4.1",
"@docusaurus/preset-classic": "2.4.1"
```

- docusaurus-openapi-docs 

```
"docusaurus-plugin-openapi-docs": "v2.0.0-beta.3",
"docusaurus-theme-openapi-docs": "v2.0.0-beta.3",
```

You can try with tha main branch
https://github.com/premAI-io/dev-portal

**Comment by sserrata** [comment]
Hi @tiero, typically these show up whenever a given page throws an error that would typically appear in the browser console error logs. That said, we've tried to address such error since your issue was originally opened. Please try a more recent release and feel free to reopen this issue if the problem still exists. Thanks!
