### ISSUE TITLE
Can  add a search function at the top of the left directory？

### ISSUE THREAD

**Issue by lys623** [PaloAltoNetworks/docusaurus-openapi-docs#782]
Type diagram：

![image](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/assets/4364314/9736a1e9-7e74-480a-8b4d-7b2da4874010)

https://developer.grab.com/docs/grabfood/api/v1-1-3/#tag/update-menu-noti

**Comment by sserrata** [comment]
Hi @lys623, you may also want to consider opening this FR with Docusaurus itself, since the broader community could likely benefit from this functionality, even outside of API docs. IIRC, a Docusaurus maintainer tried introducing this in the early days but the team decided to postpone it - should be in an old PR if you want to look for it.
